[project]
name = "analytics-api"
version = "0.1.0"
description = "Analytics REST API service"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "sqlalchemy>=2.0.0",
    "asyncpg>=0.29.0",
    "structlog>=23.2.0",
    "analytics-core",
    "api-common",
    "observability",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"