name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: 🏗️ Affected Service
      description: Which service is affected by this bug?
      options:
        - analytics-api
        - data-ingestion
        - ml-inference
        - reporting-engine
        - batch-processor
        - analytics-core (lib)
        - data-processing (lib)
        - ml-models (lib)
        - api-common (lib)
        - config (lib)
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks important functionality
        - Critical - System down or data loss
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Environment details
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04]
        - Python Version: [e.g. 3.11.5]
        - Docker Version: [e.g. 24.0.6]
        - Browser (if applicable): [e.g. Chrome 118.0]
      value: |
        - OS: 
        - Python Version: 
        - Docker Version: 
        - Browser (if applicable): 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: If applicable, add relevant error logs or stack traces
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am willing to help test a fix for this bug
          required: false