blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/datablogin/analytics-backend-monorepo/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 📚 Documentation
    url: https://github.com/datablogin/analytics-backend-monorepo/blob/main/README.md
    about: Check our documentation for setup instructions and API references
  - name: 🔧 Claude Development Guide
    url: https://github.com/datablogin/analytics-backend-monorepo/blob/main/CLAUDE.md
    about: Developer guide with commands, workflows, and project structure