name: 🚀 Enhancement
description: Improve existing functionality or performance
title: "[ENHANCEMENT] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please provide details about the enhancement you'd like to see.

  - type: textarea
    id: enhancement-description
    attributes:
      label: 🚀 Enhancement Description
      description: A clear and concise description of the improvement you'd like to see.
      placeholder: Describe the enhancement...
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 📊 Current Behavior
      description: How does the system currently work in this area?
      placeholder: Describe how it works now...
    validations:
      required: true

  - type: textarea
    id: improved-behavior
    attributes:
      label: ✨ Improved Behavior
      description: How should it work after the enhancement?
      placeholder: Describe the improved behavior...
    validations:
      required: true

  - type: dropdown
    id: enhancement-type
    attributes:
      label: 🔧 Enhancement Type
      description: What type of improvement is this?
      options:
        - Performance - Faster execution, lower resource usage
        - User Experience - Better APIs, clearer responses
        - Developer Experience - Better tooling, clearer code
        - Security - Improved security measures
        - Reliability - Better error handling, resilience
        - Scalability - Handle more load, better architecture
        - Maintainability - Cleaner code, better structure
        - Monitoring - Better observability, logging
        - Configuration - More flexible configuration options
        - Documentation - Improved docs, examples
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: 🏗️ Target Service/Component
      description: Which service or component should be enhanced?
      options:
        - analytics-api
        - data-ingestion
        - ml-inference
        - reporting-engine
        - batch-processor
        - analytics-core (lib)
        - data-processing (lib)
        - ml-models (lib)
        - api-common (lib)
        - config (lib)
        - CI/CD Pipeline
        - Documentation
        - Cross-cutting (multiple services)
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: 📈 Expected Impact
      description: What level of impact would this enhancement have?
      options:
        - Low - Minor improvement for specific use cases
        - Medium - Noticeable improvement for common workflows
        - High - Significant improvement affecting most users
        - Critical - Major improvement essential for scalability
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 🎯 Benefits
      description: What are the concrete benefits of this enhancement?
      placeholder: |
        - Improved performance by X%
        - Reduced complexity in Y area
        - Better user experience for Z workflow
    validations:
      required: true

  - type: textarea
    id: implementation-approach
    attributes:
      label: 🛠️ Implementation Approach
      description: Do you have ideas about how this could be implemented?
      placeholder: Suggest implementation approaches, technologies, or patterns...

  - type: textarea
    id: metrics
    attributes:
      label: 📊 Success Metrics
      description: How would we measure the success of this enhancement?
      placeholder: |
        - Response time reduced from X to Y
        - Memory usage decreased by Z%
        - Developer setup time reduced to X minutes

  - type: textarea
    id: risks
    attributes:
      label: ⚠️ Risks and Considerations
      description: What risks or challenges might this enhancement introduce?
      placeholder: Breaking changes, performance impacts, complexity increases, etc.

  - type: dropdown
    id: effort
    attributes:
      label: 🛠️ Estimated Effort
      description: What do you think the implementation effort might be?
      options:
        - Small - A few hours of work
        - Medium - 1-3 days of work
        - Large - 1-2 weeks of work
        - Extra Large - More than 2 weeks
        - Unknown - Need technical investigation
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the enhancement (examples, references, etc.)
      placeholder: Links to similar implementations, performance benchmarks, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this enhancement hasn't been suggested before
          required: true
        - label: I have provided clear benefits and success criteria
          required: true
        - label: I am available to provide additional clarification if needed
          required: false
        - label: I am willing to help test this enhancement when implemented
          required: false