apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
  namespace: streaming-analytics
  labels:
    app: streaming-analytics
data:
  # Environment
  STREAMING_ENVIRONMENT: "production"
  STREAMING_LOG_LEVEL: "INFO"
  STREAMING_ENABLE_TRACING: "true"
  STREAMING_TRACE_SAMPLING_RATE: "0.1"
  
  # Kafka configuration
  STREAMING_KAFKA__BOOTSTRAP_SERVERS: '["kafka-broker-1:9092","kafka-broker-2:9092","kafka-broker-3:9092"]'
  STREAMING_KAFKA__SECURITY_PROTOCOL: "SASL_SSL"
  STREAMING_KAFKA__SASL_MECHANISM: "PLAIN"
  STREAMING_KAFKA__PRODUCER_CONFIG__ACKS: "all"
  STREAMING_KAFKA__PRODUCER_CONFIG__RETRIES: "3"
  STREAMING_KAFKA__PRODUCER_CONFIG__ENABLE_IDEMPOTENCE: "true"
  STREAMING_KAFKA__PRODUCER_CONFIG__COMPRESSION_TYPE: "gzip"
  STREAMING_KAFKA__CONSUMER_CONFIG__AUTO_OFFSET_RESET: "earliest"
  STREAMING_KAFKA__CONSUMER_CONFIG__ENABLE_AUTO_COMMIT: "false"
  STREAMING_KAFKA__CONSUMER_CONFIG__MAX_POLL_RECORDS: "500"
  STREAMING_KAFKA__ENABLE_DEAD_LETTER_QUEUE: "true"
  
  # Stream processing configuration
  STREAMING_STREAM_PROCESSING__DEFAULT_WINDOW_SIZE_MS: "60000"
  STREAMING_STREAM_PROCESSING__ALLOWED_LATENESS_MS: "10000"
  STREAMING_STREAM_PROCESSING__PARALLELISM: "8"
  STREAMING_STREAM_PROCESSING__MAX_BATCH_SIZE: "1000"
  STREAMING_STREAM_PROCESSING__PROCESSING_TIMEOUT_MS: "30000"
  STREAMING_STREAM_PROCESSING__STATE_BACKEND: "rocksdb"
  STREAMING_STREAM_PROCESSING__CHECKPOINT_INTERVAL_MS: "60000"
  STREAMING_STREAM_PROCESSING__RETRY_ATTEMPTS: "3"
  STREAMING_STREAM_PROCESSING__ENABLE_DEAD_LETTER_QUEUE: "true"
  
  # WebSocket configuration
  STREAMING_WEBSOCKET__HOST: "0.0.0.0"
  STREAMING_WEBSOCKET__PORT: "8765"
  STREAMING_WEBSOCKET__MAX_CONNECTIONS: "10000"
  STREAMING_WEBSOCKET__PING_INTERVAL: "20"
  STREAMING_WEBSOCKET__PING_TIMEOUT: "10"
  STREAMING_WEBSOCKET__REQUIRE_AUTH: "true"
  STREAMING_WEBSOCKET__AUTH_TIMEOUT_SECONDS: "30"
  STREAMING_WEBSOCKET__ENABLE_RATE_LIMITING: "true"
  STREAMING_WEBSOCKET__RATE_LIMIT_PER_MINUTE: "100"
  STREAMING_WEBSOCKET__USE_SSL: "true"
  
  # Real-time ML configuration
  STREAMING_REALTIME_ML__MODEL_CACHE_SIZE: "20"
  STREAMING_REALTIME_ML__MODEL_WARM_UP_SAMPLES: "100"
  STREAMING_REALTIME_ML__MODEL_REFRESH_INTERVAL_SECONDS: "300"
  STREAMING_REALTIME_ML__BATCH_INFERENCE: "true"
  STREAMING_REALTIME_ML__MAX_BATCH_SIZE: "64"
  STREAMING_REALTIME_ML__BATCH_TIMEOUT_MS: "50"
  STREAMING_REALTIME_ML__FEATURE_CACHE_TTL_SECONDS: "300"
  STREAMING_REALTIME_ML__MAX_LATENCY_MS: "50"
  STREAMING_REALTIME_ML__THROUGHPUT_TARGET_PER_SECOND: "2000"
  
  # Monitoring configuration
  STREAMING_MONITORING__METRICS_INTERVAL_SECONDS: "10"
  STREAMING_MONITORING__DETAILED_METRICS: "true"
  STREAMING_MONITORING__LATENCY_WARNING_MS: "100"
  STREAMING_MONITORING__LATENCY_CRITICAL_MS: "1000"
  STREAMING_MONITORING__THROUGHPUT_WARNING_THRESHOLD: "0.8"
  STREAMING_MONITORING__ERROR_RATE_WARNING_THRESHOLD: "0.01"
  STREAMING_MONITORING__ERROR_RATE_CRITICAL_THRESHOLD: "0.05"
  STREAMING_MONITORING__ENABLE_AUTO_SCALING: "true"
  STREAMING_MONITORING__SCALE_UP_THRESHOLD: "0.8"
  STREAMING_MONITORING__SCALE_DOWN_THRESHOLD: "0.3"
  STREAMING_MONITORING__MIN_INSTANCES: "2"
  STREAMING_MONITORING__MAX_INSTANCES: "20"
  STREAMING_MONITORING__COOLDOWN_PERIOD_SECONDS: "300"
  
  # Topics configuration
  STREAMING_DEFAULT_TOPIC_PARTITIONS: "6"
  STREAMING_DEFAULT_TOPIC_REPLICATION_FACTOR: "3"
  STREAMING_EVENTS_TOPIC: "analytics-events"
  STREAMING_METRICS_TOPIC: "streaming-metrics"
  STREAMING_ALERTS_TOPIC: "streaming-alerts"
  STREAMING_ML_PREDICTIONS_TOPIC: "ml-predictions"
  
  # Database configuration
  DATABASE_HOST: "postgres-cluster.streaming-analytics.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "streaming_analytics"
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  DATABASE_POOL_TIMEOUT: "30"
  
  # Redis configuration
  REDIS_HOST: "redis-cluster.streaming-analytics.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_POOL_SIZE: "50"
  
  # OpenTelemetry configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "streaming-analytics"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=streaming-analytics,service.version=1.0.0"